PackageIdentifier: Metanorma.Metanorma
PackageVersion: 1.10.5
PackageLocale: en-US
Publisher: Ribose Group Inc.
PublisherUrl: https://metanorma.org/
PublisherSupportUrl: https://github.com/metanorma/metanorma-cli/issues
PackageName: Metanorma
PackageUrl: https://github.com/metanorma/packed-mn
License: BSD-2-Clause
ShortDescription: Metanorma is the award-winning open-source standards authoring and publishing framework. With a focus on semantic authoring and flexible output support, many standards development organizations depend on Metanorma for making their standards available to the world.
Moniker: metanorma
Tags:
  - standard
  - documentation
  - adoc
ManifestType: defaultLocale
ManifestVersion: 1.5.0
